FROM php:7.4-fpm-alpine3.12
RUN apk update && apk add --no-cache autoconf gcc g++ make gmp-dev libzip-dev icu-dev
RUN pecl install ast && docker-php-ext-enable ast
RUN mkdir -p /usr/src/php/ext/apcu && \
    curl -fsSL https://pecl.php.net/get/apcu-5.1.19.tgz | tar xvz -C "/usr/src/php/ext/apcu" --strip 1
RUN mkdir -p /usr/src/php/ext/xdebug && \
    curl -fsSL https://pecl.php.net/get/xdebug-3.0.1.tgz | tar xvz -C "/usr/src/php/ext/xdebug" --strip 1
RUN docker-php-ext-install pdo_mysql gmp zip intl apcu xdebug opcache
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
RUN mkdir -p /home/composer/.composer && chmod 0777 /home/composer/.composer
ENV COMPOSER_HOME /home/composer/.composer
RUN echo "memory_limit=256M" > /usr/local/etc/php/conf.d/docker-php-neucore.ini && \
    echo "xdebug.mode=develop,coverage,profile" >> /usr/local/etc/php/conf.d/docker-php-neucore.ini && \
    echo "apc.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-neucore.ini
