FROM php:7.4-fpm-alpine
RUN apk update && apk add gmp-dev libzip-dev
RUN mkdir -p /usr/src/php/ext/apcu && \
    curl -fsSL https://pecl.php.net/get/apcu-5.1.19.tgz | tar xvz -C "/usr/src/php/ext/apcu" --strip 1
RUN mkdir -p /usr/src/php/ext/xdebug && \
    curl -fsSL https://pecl.php.net/get/xdebug-2.9.8.tgz | tar xvz -C "/usr/src/php/ext/xdebug" --strip 1
RUN docker-php-ext-install pdo_mysql gmp zip apcu xdebug
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
RUN mkdir -p /home/composer/.composer && chmod 0777 /home/composer/.composer
ENV COMPOSER_HOME /home/composer/.composer
RUN echo "memory_limit=256M" > /usr/local/etc/php/conf.d/docker-php-neucore.ini
