<?php declare(strict_types=1);

namespace Brave\Core\Repository;

use Brave\Core\Entity\Alliance;

/**
 * AllianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Alliance|null find($id, $lockMode = null, $lockVersion = null)
 * @method Alliance|null findOneBy(array $criteria, array $orderBy = null)
 * @method Alliance[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class AllianceRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Constructor that makes this class autowireable.
     */
    public function __construct(\Doctrine\ORM\EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getClassMetadata(Alliance::class));
    }

    /**
     * @return \Brave\Core\Entity\Alliance[]
     */
    public function getAllWithGroups()
    {
        return $this->createQueryBuilder('a')
            ->join('a.groups', 'g')
            ->andWhere('g.id IS NOT NULL')
            ->orderBy('a.name')
            ->getQuery()
            ->getResult();
    }
}
