<?php declare(strict_types=1);

namespace Brave\Core\Repository;

use Brave\Core\Entity\Character;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Character|null find($id, $lockMode = null, $lockVersion = null)
 * @method Character|null findOneBy(array $criteria, array $orderBy = null)
 * @method Character[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class CharacterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Constructor that makes this class autowireable.
     */
    public function __construct(\Doctrine\ORM\EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getClassMetadata(Character::class));
    }

    /**
     *
     * @param string $name
     * @return \Brave\Core\Entity\Character[]
     */
    public function findByNamePartialMatch($name)
    {
        return $this->createQueryBuilder('c')
            ->where('c.name LIKE :name')
            ->addOrderBy('c.name', 'ASC')
            ->setParameter('name', "%$name%")
            ->getQuery()
            ->getResult();
    }
}
