<?php declare(strict_types=1);

namespace Brave\Core\Repository;

use Brave\Core\Entity\Corporation;

/**
 * CorporationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Corporation|null find($id, $lockMode = null, $lockVersion = null)
 * @method Corporation|null findOneBy(array $criteria, array $orderBy = null)
 * @method Corporation[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class CorporationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Brave\Core\Entity\Corporation[]
     */
    public function getAllWithGroups()
    {
        return $this->createQueryBuilder('c')
            ->join('c.groups', 'g')
            ->andWhere('g.id IS NOT NULL')
            ->orderBy('c.name')
            ->getQuery()
            ->getResult();
    }
}
