<?php declare(strict_types=1);

namespace Brave\Core\Entity;

/**
 * CorporationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Constructor that makes this class autowireable.
     */
    public function __construct(\Doctrine\ORM\EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getMetadataFactory()->getMetadataFor(Corporation::class));
    }

    /**
     *
     * {@inheritDoc}
     * @see \Doctrine\ORM\EntityRepository::find()
     * @return \Brave\Core\Entity\Corporation|null
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }

    /**
     *
     * @return \Brave\Core\Entity\Corporation[]
     */
    public function getAllWithGroups()
    {
        // TODO is there a better way?

        return $this->createQueryBuilder('c')
            ->join('c.groups', 'g')
            ->andWhere('g.id IS NOT NULL')
            ->orderBy('c.name')
            ->getQuery()
            ->getResult();
    }
}
