<?php declare(strict_types=1);

namespace Brave\Core\Entity;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Constructor that makes this class autowireable.
     */
    public function __construct(\Doctrine\ORM\EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getMetadataFactory()->getMetadataFor(Group::class));
    }

    /**
     *
     * {@inheritDoc}
     * @see \Doctrine\ORM\EntityRepository::find()
     * @return \Brave\Core\Entity\Group|null
     */
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        return parent::find($id, $lockMode, $lockVersion);
    }

    /**
     *
     * {@inheritDoc}
     * @see \Doctrine\ORM\EntityRepository::findOneBy()
     * @return \Brave\Core\Entity\Group|null
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy);
    }
}
