<?php

namespace Brave\Core\Entity;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Constructor that makes this class autowireable.
     */
    public function __construct(\Doctrine\ORM\EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getMetadataFactory()->getMetadataFor(Role::class));
    }

    /**
     *
     * {@inheritDoc}
     * @see \Doctrine\ORM\EntityRepository::findOneBy()
     * @return \Brave\Core\Entity\Role|null
     */
    public function findOneBy(array $criteria, array $orderBy = null)
    {
        return parent::findOneBy($criteria, $orderBy);
    }

    /**
     *
     * {@inheritDoc}
     * @see \Doctrine\ORM\EntityRepository::findBy()
     * @return \Brave\Core\Entity\Role[]
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }
}
