<?php

declare(strict_types=1);

namespace Neucore\Repository;

use Doctrine\ORM\EntityRepository;
use Neucore\Entity\Alliance;
use Neucore\Util\Database;

/**
 * AllianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Alliance|null find($id, $lockMode = null, $lockVersion = null)
 * @method Alliance|null findOneBy(array $criteria, array $orderBy = null)
 * @method Alliance[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class AllianceRepository extends EntityRepository
{
    /**
     * @return Alliance[]
     */
    public function getAllWithGroups(): array
    {
        return $this->createQueryBuilder('a')
            ->join('a.groups', 'g')
            ->andWhere('g.id IS NOT NULL')
            ->orderBy('a.name')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Alliance[]
     * @see CorporationRepository::findByNameOrTickerPartialMatch
     */
    public function findByNameOrTickerPartialMatch(string $search): array
    {
        $search = Database::escapeForLike($search);

        // For some reason there's an error "SQLSTATE[HY093]: Invalid parameter number: number
        // of bound variables does not match number of tokens" when both are used in the same
        // query with MariaDB if the sql mode includes NO_BACKSLASH_ESCAPES and "ESCAPE" is used
        // in the query.

        $query1 = $this->createQueryBuilder('a')
            ->where("a.name LIKE :name ESCAPE '\'")
            ->addOrderBy('a.name', 'ASC')
            ->setParameter('name', "%$search%");
        $result1 = $query1->getQuery()->getResult();

        $query2 = $this->createQueryBuilder('a')
            ->where("a.ticker LIKE :ticker ESCAPE '\'")
            ->addOrderBy('a.name', 'ASC')
            ->setParameter('ticker', "%$search%");
        $result2 = $query2->getQuery()->getResult();

        return array_merge($result1, $result2);
    }
}
