<?php

declare(strict_types=1);

namespace Neucore\Repository;

use Doctrine\ORM\EntityRepository;
use Neucore\Entity\Alliance;

/**
 * AllianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Alliance|null find($id, $lockMode = null, $lockVersion = null)
 * @method Alliance|null findOneBy(array $criteria, array $orderBy = null)
 * @method Alliance[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class AllianceRepository extends EntityRepository
{
    /**
     * @return Alliance[]
     */
    public function getAllWithGroups(): array
    {
        return $this->createQueryBuilder('a')
            ->join('a.groups', 'g')
            ->andWhere('g.id IS NOT NULL')
            ->orderBy('a.name')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Alliance[]
     */
    public function findByNameOrTickerPartialMatch(string $search): array
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.name LIKE :search')
            ->orWhere('a.ticker LIKE :search')
            ->addOrderBy('a.name', 'ASC')
            ->setParameter('search', "%$search%");

        return $query->getQuery()->getResult();
    }
}
