<?php

declare(strict_types=1);

namespace Neucore\Repository;

use Doctrine\ORM\EntityRepository;
use Neucore\Entity\Character;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Character|null find($id, $lockMode = null, $lockVersion = null)
 * @method Character|null findOneBy(array $criteria, array $orderBy = null)
 * @method Character[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class CharacterRepository extends EntityRepository
{
    /**
     * @return Character[]
     */
    public function findByNamePartialMatch(string $name, bool $mainOnly): array
    {
        $query = $this->createQueryBuilder('c')
            ->where('c.name LIKE :name')
            ->addOrderBy('c.name', 'ASC')
            ->setParameter('name', "%$name%");
        if ($mainOnly) {
            $query->andWhere('c.main = :main')
                ->setParameter('main', true);
        }
        return $query->getQuery()->getResult();
    }
}
