<?php

declare(strict_types=1);

namespace Neucore\Repository;

use Doctrine\ORM\EntityRepository;
use Neucore\Data\SearchResult;
use Neucore\Entity\Player;
use Neucore\Util\Database;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Player|null find($id, $lockMode = null, $lockVersion = null)
 * @method Player|null findOneBy(array $criteria, array $orderBy = null)
 * @method Player[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 *
 * @psalm-suppress MissingTemplateParam
 */
class PlayerRepository extends EntityRepository
{
    /**
     * @return Player[]
     */
    public function findWithoutCharacters(): array
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.characters', 'c')
            ->andWhere('c.id IS NULL')
            ->orderBy('p.name')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Player[]
     */
    public function findWithCharacters(): array
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.characters', 'c')
            ->andWhere('c.id IS NOT NULL')
            ->orderBy('p.name')
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Player[]
     */
    public function findWithCharactersAndStatus(string $status): array
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.characters', 'c')
            ->andWhere('c.id IS NOT NULL')
            ->andWhere('p.status = :status')
            ->setParameter('status', $status)
            ->orderBy('p.name')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int[] $allianceIds
     * @return int[] Player IDs
     */
    public function findInAlliances(array $allianceIds): array
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p.id')
            ->distinct()
            ->leftJoin('p.characters', 'char')
            ->leftJoin('char.corporation', 'corp')
            ->andWhere($qb->expr()->in('corp.alliance', ':ids'))
            ->setParameter('ids', $allianceIds);

        return array_map(function (array $player) {
            return (int)$player['id'];
        }, $qb->getQuery()->getResult());
    }

    /**
     * @param int[] $corporationIds
     * @return int[] Player IDs
     */
    public function findInCorporations(array $corporationIds): array
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p.id')
            ->distinct()
            ->leftJoin('p.characters', 'c')
            ->andWhere($qb->expr()->in('c.corporation', ':ids'))
            ->setParameter('ids', $corporationIds);

        return array_map(function (array $player) {
            return (int)$player['id'];
        }, $qb->getQuery()->getResult());
    }

    /**
     * @return Player[]
     */
    public function findInCorporation(int $corporationId): array
    {
        // Note: getResult() eliminates duplicates.
        return $this->createQueryBuilder('p')
            ->leftJoin('p.characters', 'c')
            ->andWhere('c.id IS NOT NULL')
            ->andWhere('c.corporation = :corp')
            ->setParameter('corp', $corporationId)
            ->orderBy('p.name')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int[] $groupIds
     * @return Player[]
     */
    public function findWithGroups(array $groupIds): array
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->leftJoin('p.groups', 'g')
            ->where($qb->expr()->in('g.id', ':ids'))
            ->orderBy('p.id')
            ->setParameter('ids', $groupIds)
            ->getQuery()
            ->getResult();
    }

    /**
     * @return Player[]
     */
    public function findWithRole(int $roleId): array
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->leftJoin('p.roles', 'r')
            ->where($qb->expr()->eq('r.id', ':id'))
            ->orderBy('p.id')
            ->setParameter('id', $roleId)
            ->getQuery()
            ->getResult();
    }

    /**
     * Return all players who have characters in one of the provided corporation
     * and do not belong to one of the provided players.
     *
     * @param array $corporationIds Player accounts with characters in these corporations
     * @param Player[] $players Exclude these players
     * @return Player[]
     */
    public function findInCorporationsWithExcludes(array $corporationIds, array $players): array
    {
        if (empty($corporationIds)) {
            return [];
        }

        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.characters', 'c');

        $qb->andWhere($qb->expr()->in('c.corporation', ':corporationIds'))
            ->setParameter('corporationIds', $corporationIds);

        if (! empty($players)) {
            $qb->andWhere($qb->expr()->notIn('p.id', ':playerIds'))
                ->setParameter('playerIds', $players);
        }

        $qb->orderBy('p.name');

        return $qb->getQuery()->getResult();
    }

    /**
     * Return all players who have characters that are not in NPC corporations,
     * not in a corporation from the provided list
     * and are not one of the provided players.
     *
     * @param array $corporationIds Exclude these corporations
     * @param Player[] $players Exclude these players
     * @return Player[]
     */
    public function findNotInNpcCorporationsWithExcludes(array $corporationIds, array $players): array
    {
        $qb = $this->createQueryBuilder('p')
            ->leftJoin('p.characters', 'c');

        $qb->andWhere($qb->expr()->gt('c.corporation', ':npc'))
            ->setParameter('npc', 2000000);

        if (! empty($corporationIds)) {
            $qb->andWhere($qb->expr()->notIn('c.corporation', ':corporationIds'))
                ->setParameter('corporationIds', $corporationIds);
        }

        if (! empty($players)) {
            $qb->andWhere($qb->expr()->notIn('p.id', ':playerIds'))
                ->setParameter('playerIds', $players);
        }

        $qb->orderBy('p.name');

        return $qb->getQuery()->getResult();
    }

    /**
     * @return SearchResult[]
     */
    public function findCharacters(string $nameOrId, bool $currentOnly): array
    {
        $nameOrIdForLike = Database::escapeForLike($nameOrId);

        // current characters
        $query1 = $this
            ->createQueryBuilder('p')
            ->select([
                'c.id AS character_id',
                'c.name AS character_name',
                'p.id AS player_id',
                'p.name AS player_name',
            ])
            ->leftJoin('p.characters', 'c')
            ->where("c.name LIKE :name ESCAPE '\'")
            ->orWhere('c.id = :id')
            ->orderBy('c.name', 'ASC')
            ->setParameter('name', "%$nameOrIdForLike%")
            ->setParameter('id', $nameOrId);

        if (!$currentOnly) {
            // removed characters
            $query2 = $this
                ->createQueryBuilder('p')
                ->select([
                    'rc.characterId AS character_id',
                    'rc.characterName AS character_name',
                    'p.id AS player_id',
                    'p.name AS player_name',
                ])
                ->distinct()
                ->leftJoin('p.removedCharacters', 'rc')
                ->where("rc.characterName LIKE :name ESCAPE '\'")
                ->orWhere('rc.characterId = :id')
                ->orderBy('rc.characterName', 'ASC')
                ->setParameter('name', "%$nameOrIdForLike%")
                ->setParameter('id', $nameOrId);

            // character name changes
            $query3 = $this
                ->createQueryBuilder('p')
                ->select([
                    'c.id AS character_id',
                    #'IDENTITY(ccn.character) AS character_id',
                    'ccn.oldName AS character_name',
                    'p.id AS player_id',
                    'p.name AS player_name',
                ])
                ->leftJoin('p.characters', 'c')
                ->leftJoin('c.characterNameChanges', 'ccn')
                ->where("ccn.oldName LIKE :name ESCAPE '\'")
                ->orderBy('ccn.oldName', 'ASC')
                ->setParameter('name', "%$nameOrIdForLike%");
        }

        $result = $query1->getQuery()->getResult();
        if (!$currentOnly) {
            /* @phan-suppress-next-line PhanPossiblyUndeclaredVariable */
            $result = array_merge($result, $query2->getQuery()->getResult(), $query3->getQuery()->getResult());
        }

        // remove duplicates
        $finalResult = [];
        $idents = [];
        foreach ($result as $item) {
            $charId = (int)$item['character_id'];
            $charName = (string)$item['character_name'];
            $playerId = (int)$item['player_id'];
            $compare = "$charId|$playerId|$charName";
            if (!in_array($compare, $idents)) {
                $idents[] = $compare;
                $finalResult[] = new SearchResult($charId, $charName, $playerId, (string)$item['player_name']);
            }
        }

        // sort
        if (!$currentOnly) {
            uasort($finalResult, function (SearchResult $a, SearchResult $b) {
                $nameA = mb_strtolower($a->characterName);
                $nameB = mb_strtolower($b->characterName);
                $playerNameA = mb_strtolower($a->playerName);
                $playerNameB = mb_strtolower($b->playerName);
                if ($nameA < $nameB) {
                    return -1;
                } elseif ($nameA > $nameB) {
                    return 1;
                } elseif ($playerNameA < $playerNameB) {
                    return -1;
                } elseif ($playerNameA > $playerNameB) {
                    return 1;
                }
                return 0;
            });
        }

        return array_values($finalResult);
    }

    /**
     * @return int[] Player IDs
     */
    public function findPlayersOfCharacters(array $characterIds): array
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p.id')->distinct()
            ->leftJoin('p.characters', 'c')
            ->where($qb->expr()->in('c.id', ':ids'))
            ->setParameter('ids', $characterIds);

        return array_map(function (array $player) {
            return (int)$player['id'];
        }, $qb->getQuery()->getResult());
    }

    /**
     * @return int[] Player IDs
     */
    public function findPlayersOfRecentlyAddedCharacters(int $createdWithinDays): array
    {
        $qb = $this->createQueryBuilder('p');
        $qb->select('p.id')->distinct()
            ->leftJoin('p.characters', 'c')
            ->where('c.created >= :days')
            ->setParameter('days', (new \DateTime("now -$createdWithinDays days"))->format('Y-m-d H:i:s'));

        return array_map(function (array $player) {
            return (int)$player['id'];
        }, $qb->getQuery()->getResult());
    }
}
