<?php declare(strict_types=1);

namespace Neucore\Repository;

use Neucore\Entity\Character;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Character|null find($id, $lockMode = null, $lockVersion = null)
 * @method Character|null findOneBy(array $criteria, array $orderBy = null)
 * @method Character[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class CharacterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $name
     * @return \Neucore\Entity\Character[]
     */
    public function findByNamePartialMatch($name)
    {
        return $this->createQueryBuilder('c')
            ->where('c.name LIKE :name')
            ->addOrderBy('c.name', 'ASC')
            ->setParameter('name', "%$name%")
            ->getQuery()
            ->getResult();
    }
}
