<?php declare(strict_types=1);

namespace Neucore\Repository;

use Neucore\Entity\Group;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Group|null find($id, $lockMode = null, $lockVersion = null)
 * @method Group|null findOneBy(array $criteria, array $orderBy = null)
 * @method Group[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
}
